version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finance-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./finance.db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - CORS_ORIGINS=http://localhost:3000
      - LM_STUDIO_URL=${LM_STUDIO_URL:-http://host.docker.internal:1234/v1}
      - LM_STUDIO_ENABLED=${LM_STUDIO_ENABLED:-false}
    volumes:
      - ./backend/data:/app/data
      - ./backend/app:/app/app
    networks:
      - finance-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finance-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - finance-network
    restart: unless-stopped

networks:
  finance-network:
    driver: bridge

volumes:
  backend-data:
